# Generated by Django 5.1.15 on 2026-06-03 04:12

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_grades_otps_remove_usermaster_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='user_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='db.grades')),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeWords',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_date', models.DateField()),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.grades')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.words')),
            ],
            options={
                'db_table': 'daily_challenge_words',
                'unique_together': {('challenge_date', 'grade', 'word')},
            },
        ),
    ]
