# Generated by Django 5.1.15 on 2026-06-06 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_kids_date_of_birth_usermaster_last_login_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['grade'], name='words_grade_i_1c6d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['difficulty'], name='words_difficu_9e36b5_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['is_active'], name='words_is_acti_ace77c_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['grade', 'difficulty'], name='words_grade_i_be0c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['grade', 'is_active'], name='words_grade_i_30d8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['word'], name='words_word_8e8fba_idx'),
        ),
    ]
