# Generated by Django 5.1.15 on 2026-06-06 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_words_difficulty_alter_words_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('skipped_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='db.kids')),
            ],
            options={
                'db_table': 'practice_attempts',
            },
        ),
        migrations.CreateModel(
            name='PracticeAttemptAnswers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typed_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.words')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='db.practiceattempts')),
            ],
            options={
                'db_table': 'practice_attempt_answers',
            },
        ),
        migrations.CreateModel(
            name='WordAudios',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pronunciation_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('part_of_speech_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('origin_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='db.words')),
            ],
            options={
                'db_table': 'word_audios',
            },
        ),
        migrations.CreateModel(
            name='KidWordProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to='db.kids')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_progress', to='db.words')),
            ],
            options={
                'db_table': 'kid_word_progress',
                'indexes': [models.Index(fields=['kid'], name='kid_word_pr_kid_id_ecc517_idx'), models.Index(fields=['word'], name='kid_word_pr_word_id_5c9d4c_idx'), models.Index(fields=['kid', 'word'], name='kid_word_pr_kid_id_d97890_idx')],
                'unique_together': {('kid', 'word')},
            },
        ),
    ]
