# Generated by Django 5.1.15 on 2026-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_usermaster_coins_usermaster_referral_code_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='voice_status',
            field=models.CharField(choices=[('GENERATED', 'GENERATED'), ('PENDING', 'PENDING')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
