# Generated by Django 5.1.15 on 2026-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_words_voice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
