# Generated by Django 5.1.15 on 2026-06-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_usermaster_dob_usermaster_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
