# Generated by Django 5.1.15 on 2026-06-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_usermaster_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
