# Generated by Django 5.1.15 on 2026-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_usermaster_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='subject',
            field=models.CharField(default='English', max_length=255),
        ),
    ]
