# Generated by Django 5.1.15 on 2026-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_words_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='concept',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='hint',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
