# Generated by Django 5.1.15 on 2026-06-14 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_words_concept_words_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceattempts',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyChallengeAttempts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_date', models.DateField()),
                ('total_words', models.IntegerField(default=10)),
                ('attempted_words', models.IntegerField(default=0)),
                ('correct_words', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='IN_PROGRESS', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.grades')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_attempts', to='db.kids')),
            ],
            options={
                'db_table': 'daily_challenge_attempts',
                'unique_together': {('kid', 'challenge_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeWordAttempts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_attempts', to='db.dailychallengeattempts')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.words')),
            ],
            options={
                'db_table': 'daily_challenge_word_attempts',
                'unique_together': {('challenge_attempt', 'word')},
            },
        ),
    ]
