# Generated by Django 5.1.15 on 2026-06-14 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_practiceattempts_total_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeAttemptAnswers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typed_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_attempts', to='db.dailychallengeattempts')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.words')),
            ],
            options={
                'db_table': 'daily_challenge_attempt_answers',
                'unique_together': {('challenge_attempt', 'word')},
            },
        ),
        migrations.DeleteModel(
            name='DailyChallengeWordAttempts',
        ),
    ]
