# Generated by Django 5.1.15 on 2026-07-01 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('audience', models.CharField(choices=[('ALL_USERS', 'ALL_USERS'), ('PARENTS', 'PARENTS'), ('KIDS', 'KIDS'), ('GRADES', 'GRADES'), ('SPECIFIC_USERS', 'SPECIFIC_USERS'), ('SPECIFIC_KIDS', 'SPECIFIC_KIDS'), ('ACTIVE_USERS', 'ACTIVE_USERS'), ('INACTIVE_USERS', 'INACTIVE_USERS')], max_length=50)),
                ('grade_ids', models.JSONField(blank=True, default=list)),
                ('user_ids', models.JSONField(blank=True, default=list)),
                ('kid_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENDING', 'SENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_campaign',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipients',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('PUSH', 'PUSH'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('WHATSAPP', 'WHATSAPP'), ('IN_APP', 'IN_APP')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('OPENED', 'OPENED')], default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='db.notificationcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_recipients',
            },
        ),
    ]
