# Generated by Django 5.1.15 on 2026-07-05 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_notificationtemplate_notificationcampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
