# Generated by Django 5.1.15 on 2026-07-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_alter_usermaster_email_alter_usermaster_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otps',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='otps',
            name='identifier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
