# Generated by Django 5.1.15 on 2026-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_remove_otps_mobile_number_otps_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
