# Generated by Django 5.1.15 on 2026-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_alter_words_word'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='words',
            constraint=models.UniqueConstraint(fields=('grade', 'word'), name='unique_grade_word'),
        ),
    ]
