# Generated by Django 5.1.15 on 2026-07-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_subjects_words_category_topics'),
        ('db', '0021_words_unique_grade_word'),
    ]

    operations = [
    ]
