# Generated by Django 5.1.15 on 2026-07-27 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_merge_20260724_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tournament_type', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('SPECIAL', 'SPECIAL'), ('SCHOOL', 'SCHOOL'), ('STATE', 'STATE'), ('NATIONAL', 'NATIONAL')], max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=50)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField(default=0)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('UPCOMING', 'UPCOMING'), ('LIVE', 'LIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.subjects')),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentRewards',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_rank', models.PositiveIntegerField()),
                ('to_rank', models.PositiveIntegerField()),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('reward_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='db.tournaments')),
            ],
            options={
                'db_table': 'tournament_rewards',
            },
        ),
        migrations.CreateModel(
            name='TournamentQuestions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.words')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='db.tournaments')),
            ],
            options={
                'db_table': 'tournament_questions',
                'unique_together': {('tournament', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('skipped_answers', models.PositiveIntegerField(default=0)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('JOINED', 'JOINED'), ('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED')], default='JOINED', max_length=20)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.kids')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='db.tournaments')),
            ],
            options={
                'db_table': 'tournament_participants',
                'unique_together': {('tournament', 'kid')},
            },
        ),
        migrations.CreateModel(
            name='TournamentAnswers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typed_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='db.tournamentparticipants')),
                ('tournament_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.tournamentquestions')),
            ],
            options={
                'db_table': 'tournament_answers',
                'unique_together': {('participant', 'tournament_question')},
            },
        ),
        migrations.CreateModel(
            name='TournamentGrades',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.grades')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_grades', to='db.tournaments')),
            ],
            options={
                'db_table': 'tournament_grades',
                'unique_together': {('tournament', 'grade')},
            },
        ),
    ]
