# Generated by Django 5.1.15 on 2026-07-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_merge_20260724_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='is_valid',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='User who manually validated the word.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='words',
            name='validation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='validation_source',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('MANUAL', 'Manual')], db_index=True, max_length=10, null=True),
        ),
    ]
