# Generated by Django 5.1.15 on 2026-07-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_tournaments_tournamentrewards_tournamentquestions_and_more'),
        ('db', '0023_words_is_valid_words_validated_at_words_validated_by_and_more'),
    ]

    operations = [
    ]
